spring.datasource.url=jdbc:mysql://z5zm8hebixwywy9d.cbetxkdyhwsb.us-east-1.rds.amazonaws.com:3306/q08cngqrylxdztrw
spring.datasource.username=w96zdr1r0taaouk3
spring.datasource.password=ovzgsgy5lu1vf5yd
spring.jpa.hibernate.ddl-auto=update
